apiVersion: autoscaling.k8s.io/v2
kind: VerticalPodScaler
metadata:
  name: myapp-vpa
spec:
scaleTargetRef:
 apiVersion: "apps/v1"
 kind: Deployment
 name: myapp-scale-deployment
updatePolicy:
 updateMode: "Auto"
