apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-containers
        image: vijayvct/myapp:v1
        resources:
          requests: {}
        ports:
        - containerPort: 8080
