apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    name: pvc-pod
spec:
  containers:
  - name: pvc-pod-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
   - name: data
     persistentVolumeClaim:
      claimName: mypvc

