apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template: #pod template
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxapp-container
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
